version: '3.7'
services: 
    salt-master:
        build: 
            context: .
            dockerfile: master.dockerfile
        networks:
            - salt-network
        hostname: salt
        expose: 
            - "4505"
            - "4506"
        volumes: 
            - ./salt:/srv/salt:ro
    salt-minion:
        depends_on: 
            - salt-master
        links: 
            - "salt-master:salt"
        build: 
            context: .
            dockerfile: minion.dockerfile
        networks:
            - salt-network
networks:
    salt-network: